export let role = "admin";

// export const teachersData = [
//   {
//     id: 1,
//     teacherId: "T001",
//     name: "John Doe",
//     email: "john.doe@example.com",
//     photo: "",
//     subjects: ["Math", "Physics"],
//     classes: ["10A", "11B"],
//     phone: "123-456-7890",
//     address: "123 Main St",
//   },
//   {
//     id: 2,
//     teacherId: "T002",
//     name: "Jane Smith",
//     email: "jane.smith@example.com",
//     photo: "",
//     subjects: ["English", "History"],
//     classes: ["9A", "12C"],
//     phone: "987-654-3210",
//     address: "456 Elm St",
//   },
//   {
//     id: 3,
//     teacherId: "T003",
//     name: "Alice Johnson",
//     email: "alice.johnson@example.com",
//     photo: "",
//     subjects: ["Biology", "Chemistry"],
//     classes: ["10B", "11C"],
//     phone: "555-123-4567",
//     address: "789 Oak St",
//   },
//   {
//     id: 4,
//     teacherId: "T004",
//     name: "Bob Brown",
//     email: "bob.brown@example.com",
//     photo: "",
//     subjects: ["Geography", "Art"],
//     classes: ["9B", "12A"],
//     phone: "444-987-6543",
//     address: "321 Pine St",
//   },
// ];

// export const studentsData = [
//   {
//     id: 1,
//     studentId: "S001",
//     name: "Emily White",
//     email: "emily.white@example.com",
//     photo: "",
//     grade: "10",
//     phone: "123-456-7890",
//     address: "123 Maple St",
//   },
//   {
//     id: 2,
//     studentId: "S002",
//     name: "Michael Green",
//     email: "michael.green@gmail.com",
//     photo: "",
//     grade: "11",
//     phone: "987-654-3210",
//     address: "456 Cedar St",
//   },
//   {
//     id: 3,
//     studentId: "S003",
//     name: "Sarah Blue",
//     email: "sarah.blue@example.com",
//     photo: "",
//     grade: "12",
//     phone: "555-123-4567",
//     address: "789 Birch St",
//   },
//   {
//     id: 4,
//     studentId: "S004",
//     name: "David Black",
//     email: "david.black@exampl.com",
//     photo: "",
//     grade: "10",
//     phone: "444-987-6543",
//     address: "321 Spruce St",
//   },
// ];
